// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: pkg/pb/tests.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Pass   bool   `protobuf:"varint,3,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tests_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Test) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Test) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

type TestSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalTests  int32 `protobuf:"varint,1,opt,name=total_tests,json=totalTests,proto3" json:"total_tests,omitempty"`
	PassedTests int32 `protobuf:"varint,2,opt,name=passed_tests,json=passedTests,proto3" json:"passed_tests,omitempty"`
	FailedTests int32 `protobuf:"varint,3,opt,name=failed_tests,json=failedTests,proto3" json:"failed_tests,omitempty"`
}

func (x *TestSummary) Reset() {
	*x = TestSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSummary) ProtoMessage() {}

func (x *TestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSummary.ProtoReflect.Descriptor instead.
func (*TestSummary) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tests_proto_rawDescGZIP(), []int{1}
}

func (x *TestSummary) GetTotalTests() int32 {
	if x != nil {
		return x.TotalTests
	}
	return 0
}

func (x *TestSummary) GetPassedTests() int32 {
	if x != nil {
		return x.PassedTests
	}
	return 0
}

func (x *TestSummary) GetFailedTests() int32 {
	if x != nil {
		return x.FailedTests
	}
	return 0
}

var File_pkg_pb_tests_proto protoreflect.FileDescriptor

var file_pkg_pb_tests_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x48, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61,
	0x73, 0x73, 0x22, 0x74, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x65, 0x73,
	0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64,
	0x54, 0x65, 0x73, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f,
	0x74, 0x65, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x54, 0x65, 0x73, 0x74, 0x73, 0x32, 0x3d, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x28, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_tests_proto_rawDescOnce sync.Once
	file_pkg_pb_tests_proto_rawDescData = file_pkg_pb_tests_proto_rawDesc
)

func file_pkg_pb_tests_proto_rawDescGZIP() []byte {
	file_pkg_pb_tests_proto_rawDescOnce.Do(func() {
		file_pkg_pb_tests_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_tests_proto_rawDescData)
	})
	return file_pkg_pb_tests_proto_rawDescData
}

var file_pkg_pb_tests_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_tests_proto_goTypes = []any{
	(*Test)(nil),        // 0: pb.Test
	(*TestSummary)(nil), // 1: pb.TestSummary
}
var file_pkg_pb_tests_proto_depIdxs = []int32{
	0, // 0: pb.TestService.SendTestResults:input_type -> pb.Test
	1, // 1: pb.TestService.SendTestResults:output_type -> pb.TestSummary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_tests_proto_init() }
func file_pkg_pb_tests_proto_init() {
	if File_pkg_pb_tests_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_tests_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tests_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TestSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_tests_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_tests_proto_goTypes,
		DependencyIndexes: file_pkg_pb_tests_proto_depIdxs,
		MessageInfos:      file_pkg_pb_tests_proto_msgTypes,
	}.Build()
	File_pkg_pb_tests_proto = out.File
	file_pkg_pb_tests_proto_rawDesc = nil
	file_pkg_pb_tests_proto_goTypes = nil
	file_pkg_pb_tests_proto_depIdxs = nil
}
